language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7
before_script:
    # gearman
    - sudo apt-get install gearman-server libgearman-dev
    - sudo php tests/bin/enable-gearman.php
    - sudo /etc/init.d/gearman-server start
    - printf "\n"| pecl install gearman
    # worker
    - php -f tests/worker.php >/dev/null 2>/dev/null &


